In [4]:
%load_ext autoreload
%autoreload 2
from components import component, event_handler, rpc, EventBroadcaster, MessageChannel, create_component_starter, loop, testing_function


starter1, sample_writer, event, sub = testing_function()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [123]:
sub.await_message()

(101, {'step': 301})

In [31]:
starter1.incoming_rpc['com1_rpc'].send_message('test')

(0, None)

com1 received msg: test
increment: 100
increment: 100


In [41]:
starter1.outgoing_samples[0]()

300.0

In [36]:
starter1.outgoing_samples[1]()

array([[0.0431384 , 0.43907682, 0.94767357, 0.02412911],
       [0.58125246, 0.22272551, 0.18479024, 0.92540104],
       [0.9664355 , 0.57729077, 0.0012827 , 0.3068105 ],
       [0.05571936, 0.6594861 , 0.20924   , 0.99168718]])

In [40]:
event.publish(100)

In [5]:
starter1.outgoing_samples[0]

[<function components.shared_value_v2.<locals>.reader()>,
 <function components.shared_np_array_v2.<locals>.reader()>]

In [6]:
starter1.outgoing_events

{'event_from_com1': <components.EventBroadcaster at 0x7e9512b572e0>}

In [3]:
from multiprocessing import Manager
e = EventBroadcaster('r', manager=Manager())

In [4]:
e.subscrible('hi')

TypeError: Pickling an AuthenticationString object is disallowed for security reasons

In [89]:
outgoing_value_samplers1[1]()

array([[0.36650763, 0.22649892, 0.00287354, 0.3325208 ],
       [0.92830119, 0.00853183, 0.20536464, 0.31300648],
       [0.86919385, 0.38016896, 0.33703199, 0.04089972],
       [0.49505787, 0.69639318, 0.15500353, 0.81218236]])

In [97]:
incoming_rpc1['com1_rpc'].send_message(100)

(2, None)

In [104]:
event.publish(100)

In [112]:
sub = outgoing_event_broadcasters1['event_from_com1'].subscrible('main')

In [69]:
from multiprocessing import Manager
m = Manager()

In [76]:
np.random.random((4,4))

array([[0.31502383, 0.53275377, 0.35769861, 0.24113408],
       [0.45799347, 0.47265247, 0.71792013, 0.80702504],
       [0.81162576, 0.90102041, 0.24659649, 0.11053502],
       [0.50937943, 0.73129427, 0.98322232, 0.63236206]])

In [70]:
starter1, outgoing_value_samplers1, incoming_rpc1, outgoing_event_broadcasters1 = create_component_starter(

    MyTestComponent1, manager=m, loop=loop, init_kwargs={}, loop_kwargs={'ideal_interval': 1}, instantiater=None
)
starter2, outgoing_value_samplers2, incoming_rpc2, outgoing_event_broadcasters2 = create_component_starter(

    MyTestComponent2, manager=m, loop=loop, init_kwargs={}, loop_kwargs={'ideal_interval': 1}, instantiater=None
)



In [71]:

p1 = starter1(outgoing_value_samplers2, {}, outgoing_event_broadcasters2)

p2 = starter2(outgoing_value_samplers1, {"component1call": incoming_rpc1['myrpc']}, outgoing_event_broadcasters1)


hello


hello
hello
hello
hello
hello
com1 received msg: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
hello
hello
hello
hello
com1 received msg: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
hello
hello
hello
hello
com1 received msg: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [64]:
incoming_rpc1['myrpc'].send_and_await_response(np.ones((3,3)));

In [75]:
p1.terminate()

In [74]:
incoming_rpc1['myrpc'].send_and_await_response(np.ones((4,3)))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# numpy array support

In [25]:
import numpy as np
from multiprocessing import Array 
from typing import *


def ndarray_msg(typecode: Any, default_value: np.ndarray):


    flatten_arr = Array(typecode, default_value.ravel().tolist())
    dim = default_value.shape

    def assigner(value: np.ndarray):
        flatten_arr[:] = array.array(typecode, value.ravel()) # type: ignore

    def reader():
        return np.array(flatten_arr[:]).reshape(dim)

    pass

In [30]:
m = Manager()
e = EventBroadcaster('test', m, no_transform, no_transform)
sub = e.subscrible("test_sub")

In [31]:
sub.start_message_handling_thread(lambda x: x)

<Thread(Thread-154 (message_handling_loop), started 123640725087808)>

In [32]:
sub.send_and_await_response(np.zeros((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])